### ISSUE TITLE
VB Net - ZelloPTT.dll ptt.dll difference in BeginMessage

### ISSUE THREAD

**Issue by AndyW999** [zelloptt/zellowork-windows-client-sdk#8]
I have a project using ptt.dll working OK, if I try the same code using ZelloPTT.dll it does not work.

        Dim Users(1) As String
        Users(1) = EveryoneUser
        PTT.BeginMessage(Users)

Using ZelloPTT.dll I get

GetExceptionInfo-System.Runtime.InteropServices.SafeArrayTypeMismatchException(0x80131533): Specified array was not of the expected type.
   at System.StubHelpers.MngdSafeArrayMarshaler.ConvertSpaceToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
   at ZelloPTTLib.IZelloClient.BeginMessage(Array Users)

Why?

Thanks

Andy.

**Comment by EugeneP-Zello** [comment]
Hi Andy,
though ptt.dll and zelloptt.dll are not binary compatible, they share COM interfaces nearly 100%,
so the client app code should work when you switch from one version to another
Please share your test project, as we have only C++ and C# sample projects

**Comment by EugeneP-Zello** [comment]
I don't see any attachment, could you pls try again or upload it like a github repo?

**Comment by AndyW999** [comment]
Hi Eugene

Well there was an attachment sent – maybe your mail system stripped it as it was a RAR containing an exe.

I have put it in Dropbox –

https://www.dropbox.com/sh/cdxz9dt6o47cj3t/AACWoQZk1TQeHBK7whEyIjLpa?dl=0

Thanks

Andy.

**Comment by AndyW999** [comment]
Hi Eugene

Did you get the Dropbox code and have you managed to look at it?

Thanks

Andy.
